version: "2"
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: geforce2020
    restart: always    
  
  back-end:
      image: 21552472/node-image
      container_name: node-container
      restart: always
      ports: 
        - "9001:9001"
      depends_on:
        - db
      
    